### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by kvarga** [alanjcastonguay/pyforce#19]
pypi has a pyforce 1.5 uploaded 10/30/2015, but the only release i see in github is 1.4

Can we get these to match? It'd be nice to not have the confusion/cluster that was Beatbox repeat itself.

**Comment by alanjcastonguay** [comment]
Hey @kvarga sorry about that. Things got a little messy with maintainer switchover. It should be fixed up now. Please let me know if you see any problems.
