### ISSUE TITLE
describeSObjects doesn't seem to properly handle multiple sobjects being requested at the same time

### ISSUE THREAD

**Issue by blade2005** [alanjcastonguay/pyforce#26]
>>> arrays = [['Account'],['cmcloud__Incident__c'],['Service__c'],['cmcloud__Incident__c', 'Service__c', 'Account'],['cmcloud__Incident__c', 'Service__c'],['cmcloud__Incident__c', 'Account'],['Service__c', 'Account']]
    >>> for myarray in arrays:
    ...     print myarray
    ...     print svc.describeSObjects(myarray)
    ... 
    ['Account']
    [<pyforce.pyforce.SObject object at 0x7efdafb12c90>]
    ['cmcloud__Incident__c']
    [<pyforce.pyforce.SObject object at 0x7efdae69f6d0>]
    ['Service__c']
    [<pyforce.pyforce.SObject object at 0x7efdafb12a90>]
    ['cmcloud__Incident__c', 'Service__c', 'Account']
    []
    ['cmcloud__Incident__c', 'Service__c']
    []
    ['cmcloud__Incident__c', 'Account']
    []
    ['Service__c', 'Account']
    []

3 SObjects, I requested them one at a time and it works. but if I request multiples it fails.

**Comment by blade2005** [comment]
So I've been checking this out. It looks like the data is getting back from the post request. 

At the point right here we have no results.
    def describeSObjects(self, sObjectTypes):
        return DescribeSObjectsRequest(
            self.__serverUrl,
            self.sessionId,
            sObjectTypes
        ).post(self.__conn)

Looking at SoapEnvelope.post when it is executed it has all 3 datasets I requested. That was validated at https://github.com/alanjcastonguay/pyforce/blob/63218430b33241ff208113d7f740bf2715a38f47/src/pyforce/xmlclient.py#L491


This is a regression bug for changes from 1.6 to 1.7

**Comment by blade2005** [comment]
@alanjcastonguay flag this as a bug please

**Comment by alanjcastonguay** [comment]
Is this a bug which you're investigating and already creating a fix for, or one which I should start looking at?

**Comment by blade2005** [comment]
I'm investigating it. I'm gonna review my commits and see if something triggered it.

**Comment by blade2005** [comment]
Bug was introduced as part of https://github.com/alanjcastonguay/pyforce/commit/33c8d01805c4d8e44e040d2abecd8a24c6c4fad2

**Comment by blade2005** [comment]
Bug was in changing to new classes :| specifically Element

**Comment by blade2005** [comment]
PR forthcoming

**Comment by blade2005** [comment]
@alanjcastonguay If I switch it back to old style classing for just Element the problem goes away. However I'm not entirely sure what is causing the issue. I'm going to do a pr to get it in a working state in case people are using the dev branch. NOTE: This means we probably need to fix it as part of pypi)

**Comment by blade2005** [comment]
#27 will act as a fix to unbreak things.

**Comment by alanjcastonguay** [comment]
Merged, and tag 1.7.1 released on github and pypi.
