### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jantonacci** [alanjcastonguay/pyforce#33]
This is a very useful module, however Python 2 is deprecated.  Requesting an update from 2 to 3.

**Comment by jantonacci** [comment]
I cannot commit to that currently. Pyforce's ability to send emails is unique, valuable. Adding it to backlog for prioritizing.  Thanks for your time discussing this off-line, very good guidance.

**Comment by blakev** [comment]
@jantonacci we needed Python3 at work too, so I'm maintaining a Py3 version -- you can use it here: 

`pip install -e git+git@github.com:blakev/pyforce.git@feature/python3#egg=pyforce`

This is a stop-fix until I can commit to a full py2/py3 patch to the original project.

**Comment by ViViDboarder** [comment]
@blakev any chance of getting a PR cut from your fork?

**Comment by blakev** [comment]
@ViViDboarder I don't work on Salesforce stuff anymore, but if my fork still works I can clean it up for a legitimate PR. Any help testing it would be appreciated too!
